// Theme definitions for Corvus IDS dashboard.
// Each theme sets CSS custom properties on document.documentElement at runtime —
// no Tailwind rebuild needed for switching.

export type ThemeName = 'corvus' | 'cnc' | 'terminal' | 'arctic'

export interface ThemeDef {
  name: ThemeName
  label: string
  description: string
  /** Small hex colour shown in the settings picker swatch */
  swatch: string
  /** CSS custom property values to inject into :root */
  vars: Record<string, string>
}

export const THEMES: ThemeDef[] = [
  // ── Corvus (refined dark navy — original) ────────────────────────────────
  {
    name: 'corvus',
    label: 'Corvus',
    description: 'Default dark navy',
    swatch: '#0f172a',
    vars: {
      '--background':        '222 47% 8%',
      '--foreground':        '210 40% 92%',
      '--card':              '222 47% 11%',
      '--card-foreground':   '210 40% 92%',
      '--muted':             '217 33% 18%',
      '--muted-foreground':  '215 20% 55%',
      '--border':            '217 33% 20%',
      '--radius':            '0.5rem',
      '--color-online':             '#34d399',
      '--color-offline':            '#52525b',
      '--color-baselining':         '#fbbf24',
      '--color-sev-info-bg':        'rgba(63,63,70,0.8)',
      '--color-sev-info-text':      '#e4e4e7',
      '--color-sev-high-bg':        'rgba(120,53,15,0.6)',
      '--color-sev-high-text':      '#fcd34d',
      '--color-sev-crit-bg':        'rgba(127,29,29,0.6)',
      '--color-sev-crit-text':      '#fca5a5',
      '--color-bar-primary':        '#3b82f6',
      '--color-bar-secondary':      '#6366f1',
      '--color-bar-latency':        '#10b981',
      '--color-score-normal':       '#3b82f6',
      '--color-score-high':         '#f59e0b',
      '--color-score-crit':         '#ef4444',
      '--color-trained':            '#10b981',
      '--color-rejected':           '#f59e0b',
      '--color-count-trained':      '#34d399',
      '--color-count-rejected':     '#fbbf24',
      '--color-badge-danger-bg':    'rgba(239,68,68,0.2)',
      '--color-badge-danger-text':  '#f87171',
      '--color-badge-danger-bdr':   'rgba(239,68,68,0.3)',
      '--color-badge-warn-bg':      'rgba(245,158,11,0.2)',
      '--color-badge-warn-text':    '#fbbf24',
      '--color-badge-warn-bdr':     'rgba(245,158,11,0.3)',
      '--color-accent':             '#2563eb',
      '--color-accent-hover':       '#3b82f6',
      '--font-ui':                  'ui-sans-serif, system-ui, sans-serif',
    },
  },

  // ── C&C (Command & Conquer — military phosphor CRT) ──────────────────────
  {
    name: 'cnc',
    label: 'C&C',
    description: 'Military phosphor CRT',
    swatch: '#060d06',
    vars: {
      '--background':        '120 50% 3%',
      '--foreground':        '120 50% 68%',
      '--card':              '120 45% 5%',
      '--card-foreground':   '120 50% 68%',
      '--muted':             '120 35% 10%',
      '--muted-foreground':  '120 30% 32%',
      '--border':            '120 45% 13%',
      '--radius':            '0rem',
      '--color-online':             '#00ff44',
      '--color-offline':            '#1a3a1a',
      '--color-baselining':         '#ffaa00',
      '--color-sev-info-bg':        'rgba(0,50,0,0.7)',
      '--color-sev-info-text':      '#66ff66',
      '--color-sev-high-bg':        'rgba(55,28,0,0.8)',
      '--color-sev-high-text':      '#ffaa00',
      '--color-sev-crit-bg':        'rgba(65,0,0,0.8)',
      '--color-sev-crit-text':      '#ff5555',
      '--color-bar-primary':        '#00bb33',
      '--color-bar-secondary':      '#00aa55',
      '--color-bar-latency':        '#00cc44',
      '--color-score-normal':       '#00bb33',
      '--color-score-high':         '#ffaa00',
      '--color-score-crit':         '#ff2200',
      '--color-trained':            '#00bb33',
      '--color-rejected':           '#ffaa00',
      '--color-count-trained':      '#00ff44',
      '--color-count-rejected':     '#ffaa00',
      '--color-badge-danger-bg':    'rgba(180,0,0,0.25)',
      '--color-badge-danger-text':  '#ff5555',
      '--color-badge-danger-bdr':   'rgba(200,0,0,0.45)',
      '--color-badge-warn-bg':      'rgba(140,70,0,0.25)',
      '--color-badge-warn-text':    '#ffaa00',
      '--color-badge-warn-bdr':     'rgba(170,90,0,0.45)',
      '--color-accent':             '#007700',
      '--color-accent-hover':       '#009900',
      '--font-ui':                  'ui-monospace, "Courier New", monospace',
    },
  },

  // ── Terminal (classic green-on-black hacker) ──────────────────────────────
  {
    name: 'terminal',
    label: 'Terminal',
    description: 'Classic green-on-black',
    swatch: '#000000',
    vars: {
      '--background':        '0 0% 0%',
      '--foreground':        '135 100% 43%',
      '--card':              '0 0% 3%',
      '--card-foreground':   '135 100% 43%',
      '--muted':             '135 60% 7%',
      '--muted-foreground':  '135 55% 24%',
      '--border':            '135 80% 13%',
      '--radius':            '0rem',
      '--color-online':             '#00ff41',
      '--color-offline':            '#003310',
      '--color-baselining':         '#ffff00',
      '--color-sev-info-bg':        'rgba(0,25,0,0.9)',
      '--color-sev-info-text':      '#00ff41',
      '--color-sev-high-bg':        'rgba(28,18,0,0.9)',
      '--color-sev-high-text':      '#ffff00',
      '--color-sev-crit-bg':        'rgba(35,0,0,0.9)',
      '--color-sev-crit-text':      '#ff3300',
      '--color-bar-primary':        '#00ff41',
      '--color-bar-secondary':      '#00cc33',
      '--color-bar-latency':        '#00ff41',
      '--color-score-normal':       '#00ff41',
      '--color-score-high':         '#ffff00',
      '--color-score-crit':         '#ff0000',
      '--color-trained':            '#00ff41',
      '--color-rejected':           '#ffff00',
      '--color-count-trained':      '#00ff41',
      '--color-count-rejected':     '#ffff00',
      '--color-badge-danger-bg':    'rgba(100,0,0,0.35)',
      '--color-badge-danger-text':  '#ff3300',
      '--color-badge-danger-bdr':   'rgba(160,0,0,0.55)',
      '--color-badge-warn-bg':      'rgba(55,55,0,0.35)',
      '--color-badge-warn-text':    '#ffff00',
      '--color-badge-warn-bdr':     'rgba(90,90,0,0.55)',
      '--color-accent':             '#00ff41',
      '--color-accent-hover':       '#44ff66',
      '--font-ui':                  'ui-monospace, "Courier New", monospace',
    },
  },

  // ── Arctic (cold blue — sterile command center) ───────────────────────────
  {
    name: 'arctic',
    label: 'Arctic',
    description: 'Cold-blue command center',
    swatch: '#05080d',
    vars: {
      '--background':        '220 55% 5%',
      '--foreground':        '210 60% 88%',
      '--card':              '220 55% 8%',
      '--card-foreground':   '210 60% 88%',
      '--muted':             '215 45% 13%',
      '--muted-foreground':  '210 30% 48%',
      '--border':            '215 45% 18%',
      '--radius':            '0.2rem',
      '--color-online':             '#22d3ee',
      '--color-offline':            '#1e3a5f',
      '--color-baselining':         '#e879f9',
      '--color-sev-info-bg':        'rgba(15,23,42,0.9)',
      '--color-sev-info-text':      '#94a3b8',
      '--color-sev-high-bg':        'rgba(30,20,0,0.85)',
      '--color-sev-high-text':      '#fde68a',
      '--color-sev-crit-bg':        'rgba(45,0,15,0.85)',
      '--color-sev-crit-text':      '#fca5a5',
      '--color-bar-primary':        '#38bdf8',
      '--color-bar-secondary':      '#818cf8',
      '--color-bar-latency':        '#22d3ee',
      '--color-score-normal':       '#38bdf8',
      '--color-score-high':         '#fb923c',
      '--color-score-crit':         '#f43f5e',
      '--color-trained':            '#22d3ee',
      '--color-rejected':           '#fb923c',
      '--color-count-trained':      '#22d3ee',
      '--color-count-rejected':     '#fb923c',
      '--color-badge-danger-bg':    'rgba(244,63,94,0.2)',
      '--color-badge-danger-text':  '#fb7185',
      '--color-badge-danger-bdr':   'rgba(244,63,94,0.38)',
      '--color-badge-warn-bg':      'rgba(251,146,60,0.2)',
      '--color-badge-warn-text':    '#fdba74',
      '--color-badge-warn-bdr':     'rgba(251,146,60,0.38)',
      '--color-accent':             '#0ea5e9',
      '--color-accent-hover':       '#38bdf8',
      '--font-ui':                  'ui-sans-serif, system-ui, sans-serif',
    },
  },
]

export const DEFAULT_THEME: ThemeName = 'cnc'
